config/routes.rb
Rails.application.routes.draw do
  mount Root => '/'
  mount GrapeSwaggerRails::Engine => '/docs' if defined? GrapeSwaggerRails
  devise_for :users
  root to: 'top#index'
  get 'common/preview', to: 'common#preview'
  get 'common/realtime_preview', to: 'common#realtime_preview'
  get 'user_note_comments/create_comment', to: 'user_note_comments#create_comment'
  get 'user_note_comments/update_comment', to: 'user_note_comments#update_comment'
  get 'user_note_comments/destroy_comment', to: 'user_note_comments#destroy_comment'
  get 'notification', to: 'notifications#confirm'

  resources :profiles, only: %i[edit update]
  resources :notes do
    collection do
      match :index, via: %i[get post]
      match 'create_new', to: 'notes#create', via: 'post'
      get :add_favorite
      get :release_favorite
    end
  end
end

app/controllers/top_controller.rb
class TopController < ApplicationController
  def index
    return unless user_signed_in?

    info = viewable_notes.includes(:created_by_user, :comments)
                         .group_by { |n| n.updated_at.to_date }

    note_comments = viewable_notes.includes(comments: [:reply_user])
                                  .map(&:comments)
                                  .flatten
                                  .group_by { |nc| nc.updated_at.to_date }

    note_comments.each do |comment|
      info[comment[0]].present? ? info[comment[0]].push(comment[1][0]) : info.merge(Hash[*comment])
    end

    @update_info = paging(info.sort.reverse, 2)
  end

  private

  def viewable_notes
    @_viewable_notes ||= Note.current_viewable_notes(current_user.id)
  end
end

app/views/top/_update_info_for_note.html.slim
.upper-row.mb5
  - type = note.created_at == note.updated_at ? '投稿' : '更新'

  i.fas.fa-user-edit.mr3
  span = "#{ note.created_by_user.full_name }さんが"
  span.font-bold = "ノートを#{ type }"

  span.float-right = date_diff_str(note.updated_at)

.lower-row
  - if notification = current_user.note_notifications(note).last
    = link_to notification_path(notification_id: notification, note_id: note.id), class: 'top-unread-note', target: '_blank' do
      = note.title

    i.fas.fa-info-circle.created.update-top

  - else
    = link_to note.title, note_path(note), target: '_blank'

app/views/top/_update_info_for_note_comment.html.slim
.upper-row.mb5
  - type = comment.created_at == comment.updated_at ? '投稿' : '更新'

  i.fas.fa-user-edit.mr3
  span = "#{ comment.reply_user.full_name }さんが"
  span.font-bold = "コメントを#{ type }"

  span.float-right = date_diff_str(comment.updated_at)

.lower-row
  - if notification = current_user.comment_notifications(note).last
    = link_to notification_path(notification_id: notification.id, unread_comment_id: current_user.oldest_comment(note).id, note_id: notification.note.id), class: 'top-unread-comment', target: '_blank' do
      = note.title

    i.far.fa-comment.ml10.mr5
    span = "#{ note.comments.size }"
    i.fas.fa-exclamation-circle
  - else
    = link_to note.title, note_path(note), target: '_blank'

    i.far.fa-comment.ml10.mr5
    span = "#{ note.comments.size }"

app/views/top/index.html.slim
// ひとまずログインしないとコンテンツは見れないようにしておく
- if user_signed_in?
  #top
    .left-content
      p.recent-updates 最近の更新(ノート/コメント)

      #set_page
        - @update_info.each do |date, info|
          tr
            .update-date
              .date
                span.mr5 = l date, format: :long
                span = "(#{ info.size }件)"

            - info.reverse { |model| model.updated_at }.each do |i|
              tr
                .update-info.mb5
                  // ノート・コメント以外も表示することも考慮してcase使用
                  - case i.class.name
                  - when 'Note'
                    = render 'update_info_for_note', note: i
                  - when 'UserNoteComment'
                    = render 'update_info_for_note_comment', comment: i, note: i.note
                  - else

    .center.pt10.page.hidden
      = paginate @update_info

= javascript_include_tag 'top/index'


    // 後で何か実装
    // .right-content

app/views/top/index.js.erb
$(function() {
  return $("#page").infinitescroll({
    loading: {
      img: "http://www.mytreedb.com/uploads/mytreedb/loader/ajax_loader_blue_48.gif",
      msgText: "ロード中..."
    },
    navSelector: "nav.pagination",
    nextSelector: "nav.pagination a[rel=next]",
    itemSelector: "#top"
  });
});

$("#top > .left-content").append("<div class='page'><%= escape_javascript(render(@update_info)) %></div>");