config/routes.rb
Rails.application.routes.draw do
  mount Root => '/'
  mount GrapeSwaggerRails::Engine => '/docs' if defined? GrapeSwaggerRails
  devise_for :users
  root to: 'top#index'
  get 'common/preview', to: 'common#preview'
  get 'common/realtime_preview', to: 'common#realtime_preview'
  get 'user_note_comments/create_comment', to: 'user_note_comments#create_comment'
  get 'user_note_comments/update_comment', to: 'user_note_comments#update_comment'
  get 'user_note_comments/destroy_comment', to: 'user_note_comments#destroy_comment'
  get 'notification', to: 'notifications#confirm'

  resources :profiles, only: %i[edit update]
  resources :notes do
    collection do
      match :index, via: %i[get post]
      match 'create_new', to: 'notes#create', via: 'post'
      get :add_favorite
      get :release_favorite
    end
  end
end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
  before_action :user_not_authorized

  def edit
    @user = User.find(params[:id])
    only_current_user
  end

  def update
    @user = User.find(params[:id])

    ActiveRecord::Base.transaction do
      @user.update!(permit_params)
    end

    flash[:notice] = 'プロフィールを更新しました。'
    redirect_to action: :edit, id: @user.id
  rescue ActiveRecord::RecordInvalid
    render :edit
  end

  private

  def permit_params
    params.require(:user).permit(:name_first, :name_last)
  end

  def only_current_user
    return if current_user == @user

    flash[:error] = 'ログインユーザー以外の編集はできません'
    redirect_to root_url
  end
end

app/views/profiles/edit.html.slim
= render 'common/form_errors', target: @user

div.form-title
  span.under_border= "#{ t('view.profile') }#{ t('view.edit') }"

= form_with model: @user, url: profile_url do |f|
  div.profile-edit-form
    table.profile-edit-table
      th
        span.font-bold = t('activerecord.attributes.user.name_first')
        = render 'common/form_required_view'
      td = f.text_field :name_first

      th
        span.font-bold = t('activerecord.attributes.user.name_last')
        = render 'common/form_required_view'
      td = f.text_field :name_last

    = submit_tag t('view.update'), class: 'btn btn-success float-right'

= stylesheet_link_tag 'profiles/edit'