config/routes.rb
Rails.application.routes.draw do
  mount Root => '/'
  mount GrapeSwaggerRails::Engine => '/docs' if defined? GrapeSwaggerRails
  devise_for :users
  root to: 'top#index'
  get 'common/preview', to: 'common#preview'
  get 'common/realtime_preview', to: 'common#realtime_preview'
  get 'user_note_comments/create_comment', to: 'user_note_comments#create_comment'
  get 'user_note_comments/update_comment', to: 'user_note_comments#update_comment'
  get 'user_note_comments/destroy_comment', to: 'user_note_comments#destroy_comment'
  get 'notification', to: 'notifications#confirm'

  resources :profiles, only: %i[edit update]
  resources :notes do
    collection do
      match :index, via: %i[get post]
      match 'create_new', to: 'notes#create', via: 'post'
      get :add_favorite
      get :release_favorite
    end
  end
end

app/models/note.rb
# == Schema Information
#
# Table name: notes
#
#  id                 :integer          not null, primary key
#  title              :string           not null
#  content            :string           not null
#  created_by_user_id :integer
#  created_at         :datetime         not null
#  updated_at         :datetime         not null
#  public_flag        :boolean          default(TRUE), not null
#

class Note < ApplicationRecord
  after_save :create_note_notification

  belongs_to :created_by_user, class_name: 'User', inverse_of: :notes

  has_many :comments, dependent: :destroy, class_name: 'UserNoteComment'
  has_many :notifications, dependent: :destroy

  validates :title, presence: true
  validates :content, presence: true

  scope :my_notes, ->(user_id) { where(created_by_user_id: user_id) }

  acts_as_taggable

  def favorite_note?(user_id)
    User.find(user_id).favorite_notes.find_by(note_id: id).present?
  end

  def viewable_note?(user_id)
    Note.current_viewable_notes(user_id).find_by(id: id).present?
  end

  def self.current_viewable_notes(user_id)
    non_viewable_note_ids = Note.where.not(created_by_user_id: user_id).where(public_flag: false).ids
    non_viewable_note_ids.empty? ? Note.all : Note.where.not(id: non_viewable_note_ids)
  end

  def created_user?(user_id)
    created_by_user_id == user_id
  end

  def public_flag_change?
    public_flag_previous_change.present? && public_flag_previous_change[0] == false && public_flag_previous_change[1] == true
  end

  def create_note_notification
    return unless public_flag || public_flag_change?

    user_ids = User.other_user_ids(created_by_user_id)
    user_ids.each do |user_id|
      notifications.create(active_user_id: created_by_user_id, passive_user_id: user_id, kind: 'note')
    end
  end
end

app/controllers/notes_controller.rb
class NotesController < ApplicationController
  before_action :user_not_authorized

  def index
    @notes = paging(search_result, (params[:per_page] || 15))
  end

  def new
    @note = Note.new
    gon.all_tag_list = ActsAsTaggableOn::Tag.all.pluck(:name)
  end

  def create
    @note = Note.new(permit_params.merge(created_by_user_id: current_user.id))
    @note.save!
    flash[:notice] = 'ノートを登録しました。'
    redirect_to action: :show, id: @note.id
  rescue ActiveRecord::RecordInvalid
    render :new
  end

  def edit
    @note = Note.find(params[:id])
    gon.all_tag_list = ActsAsTaggableOn::Tag.all.pluck(:name)
    only_current_user
  end

  def update
    @note = Note.find(params[:id])
    @note.update!(permit_params)
    flash[:notice] = 'ノートを更新しました。'
    redirect_to action: :show, id: @note.id
  rescue ActiveRecord::RecordInvalid
    render :edit
  end

  def destroy
    @note = Note.find(params[:id])
    only_current_user
    @note.destroy
    flash[:notice] = 'ノートを削除しました。'
    redirect_to action: :index
  rescue ActiveRecord::RecordInvalid
    render :edit
  end

  def show
    @note = Note.find(params[:id])
    @comment = comments.build
    comments
    destroy_note_notification
    viewable_not_authorized
  end

  # お気に入り追加
  def add_favorite
    note = Note.find(params[:note_id])

    if note.favorite_note?(current_user.id)
      flash[:error] = 'すでにお気に入りに追加されています。'
    else
      favorite_note = current_user.favorite_notes.new(note_id: note.id)
      favorite_note.save!
      flash[:notice] = 'お気に入りに追加しました。'
    end
    redirect_to action: :show, id: note.id
  end

  # お気に入り解除
  def release_favorite
    note = Note.find(params[:note_id])

    if note.favorite_note?(current_user.id)
      current_user.favorite_notes.find_by(note_id: note.id).destroy!
      flash[:notice] = 'お気に入りを解除しました。'
    else
      flash[:error] = 'お気に入りにないため解除できません。'
    end
    redirect_to action: :show, id: note.id
  end

  private

  def permit_params
    params.require(:note).permit(:title, :content, :public_flag, :tag_list)
  end

  def only_current_user
    return if current_user == @note.created_by_user

    flash[:error] = '編集は登録者のみ可能です。'
    redirect_to action: :show, id: @note.id
  end

  def viewable_not_authorized
    return if @note.viewable_note?(current_user.id)

    flash[:error] = '閲覧不可のノートです'
    redirect_to action: :index
  end

  def search_result
    notes = Note.current_viewable_notes(current_user.id)
                .includes(:created_by_user, :taggings)
    notes = notes.my_notes(current_user.id) if ActiveRecord::Type::Boolean.new.cast(params[:my_note_flag])
    notes = notes.where(id: current_user.favorite_notes.map(&:note_id)) if ActiveRecord::Type::Boolean.new.cast(params[:favorite_note_flag])
    notes = notes.tagged_with(params[:tag_name].to_s) if params[:tag_name].present?
    @query = notes.ransack(params[:q])
    ret = @query.result.order(created_at: :DESC)
    ret
  end

  def comments
    @comments ||= @note.comments.includes(:reply_user).order(:id)
  end

  def note_params
    params.require(:note).permit(:tag_list)
  end

  def destroy_note_notification
    note_notification = current_user.passive_notifications.find_by(note_id: @note.id, kind: 'note')
    note_notification&.destroy
  end
end

app/views/notes/_description_text.html.slim
h4.fs20 Markdownについて

p.mb1o.fs12 ググればたくさん出て来ますが、割と使いそうな記法を下記に書いておきます！
p.mb20.fs12 = 'htmlタグ使えるのでこっちの方が自由度が高そう(改行を<br>でする等ができる)'

// コード挿入
h4.note-description-border ソースコードを挿入する
p 例)
p.fs12.non-margin ```
p.fs12.non-margin = "a = 1"
p.fs12 ```
p 結果)
p = markdown("```\r\na = 1'")

// 見出し
h4.mt20.note-description-border 見出しをつける
p 例)
p.fs12.non-margin #### これはH4タグです
p.fs12 ###### これはH6タグです
p 結果)
p = markdown("#### これはH4タグです")
p = markdown("###### これはH6タグです")

// 文字色変更
h4.mt20.note-description-border 文字色を変える
p 例)
p.fs12.non-margin = '<font color="Orange">オレンジ</font>'
p.fs12 = '<font color="Blue">青</font>'
p 結果)
p = markdown("<font color='Orange'>オレンジ</font>")
p = markdown("<font color='Blue'>青</font>")

// 打ち消し
h4.mt20.note-description-border 打ち消し線を入れる
p 例)
p.fs12 ~~打ち消し~~
p 結果)
p = markdown("~~打ち消し~~")

// 太文字
h4.mt20.note-description-border 太文字にする
p 例)
p.fs12 = "**太字**"
p 結果)
p = markdown("**太字**")

// 引用
h4.mt20.note-description-border 目立たせる
p 例)
p.fs12 = "> これは引用箇所です。"
p 結果)
p = markdown("> これは引用箇所です。")

// リンク
h4.mt20.note-description-border リンクを載せる
p 例)
p.fs12 = "[Yahoo!Japan](http://www.yahoo.co.jp/)"
p 結果)
p = markdown("[Yahoo!Japan](http://www.yahoo.co.jp/)")

// 画像貼り付け
h4.mt20.note-description-border 画像を貼る
p 例)
p.fs12.non-marge = "![ダミー画像](画像のURL)"
p.fs12 = "![ダミー画像](http://placehold.it/100)"
p 結果)
p = markdown("![ダミー画像](http://placehold.it/100)")

app/views/notes/_form.html.slim
- url = @note.new_record? ? create_new_notes_url : note_url
- submit_name = @note.new_record? ? t('view.new') : t('view.update')

= form_with model: @note, url: url do |f|
  table.note-form
    tr
      th
        .float-left = t('activerecord.attributes.note.public_flag')
        = render 'common/form_required_view'
      td
        .float-left.mr10 = f.check_box :public_flag, id: 'note_public_flag'
        label.non-margin.float-left for='note_public_flag' 公開する
    tr
      th
        .float-left = t('activerecord.attributes.note.title')
        = render 'common/form_required_view'
      td = f.text_field :title, class: 'title-form'
    tr
      th
        .float-left = t('activerecord.attributes.note.tag')
      td = f.text_field :tag_list, class: 'title-form', id: 'note-tags', value: @note.send(:tag_list).to_s
    tr
      th
        = t('activerecord.attributes.note.content')
        = render 'common/form_required_view'
      td.content-container
        = f.text_area :content, class: 'content-form syncscroll', id: 'markdown-content', name: 'note[content]'
        div#preview-area.syncscroll name='note[content]'
          - unless @note.new_record?
            = markdown(@note.content)

  div.float-right
    = submit_tag submit_name, class: 'btn btn-success mb10'
    - unless @note.new_record?
      = link_to t('view.destroy'), note_url(@note), class: 'btn btn-danger mb10 mr5 float-left', method: :delete, data: { confirm: t('helpers.delete_confirm') }

= javascript_include_tag 'notes/form'
= javascript_include_tag 'notes/syncscroll'

app/views/notes/_search_form.html.slim
= search_form_for @query, method: :post do |f|
  = hidden_field_tag :my_note_flag, params[:my_note_flag]
  = hidden_field_tag :favorite_note_flag, params[:favorite_note_flag]
  = hidden_field_tag :tag_name, nil
  
  = f.text_field :title_cont, placeholder: 'タイトル', class: 'mr10'

  = f.text_field :content_cont, placeholder: '内容', class: 'mr10'

  = f.select :created_by_user_id_eq, select_for_users, { include_blank: true }, { class: 'mr20', style: 'height: 26px;' }

  // ひとまず非表示
  = f.submit id: 'note_search_submit', class: 'btn btn-primary'

app/views/notes/_tag_list.html.slim
- tag_list.each_with_index do |tag, index|
  div.tag.btn-sm.btn-info
    = tag.truncate(10, omission: '...')
  = hidden_field_tag "tag_full_name_#{ index }", tag

app/views/notes/edit.html.slim
= render 'common/form_errors', target: @note

div.form-title
  span.under_border = "#{ t('view.note') }#{ t('view.update') }"
  span.note-description_button.btn-sm.btn-secondary
    = t('helpers.about_markdown')

= render 'form'

app/views/notes/index.html.slim
div.form-title.mb10
  span.under_border = "#{ t('view.note') }#{ t('view.index') }"

= render 'search_form'

div.index-search-result.mt20
  .float-left
    = link_to t('view.new'), new_note_url, class: 'btn btn-success mr10', style: 'padding: 5px 7px;'

  .float-left
    = check_box_tag('note[my_note_flag]', '', ActiveRecord::Type::Boolean.new.cast(params[:my_note_flag]))
    label.mt10.ml5 for='note_my_note_flag' Myノートのみ

  .float-left.ml10
    = check_box_tag('note[favorite_note_flag]', '', ActiveRecord::Type::Boolean.new.cast(params[:favorite_note_flag]))
    label.mt10.ml5 for='note_favorite_note_flag' お気に入りのみ

  .float-right
    p.float-left.fs25.mr3.count = @notes.total_count
    p.float-left.mt10.mr3 件中
    p.float-left.fs25.mr3.count = "#{ @notes.limit_value * @notes.offset_value / @notes.limit_value + 1 }"
    p.float-left.mt10.mr3 = '件～'
    p.float-left.fs25.mr3.count = "#{ @notes.limit_value * @notes.offset_value / @notes.limit_value + @notes.length }"
    p.float-left.mt10.mr3 = '件表示'
    / 検索条件付与してから表示するかを考える
    / = select_tag :per_page, options_for_select(per_pages_for_select, params[:per_page]), class: 'float-left per-page-select'
    / p.float-left.mt10.mr3 = '件'

table.note-list
  thead
    tr
      th
      th = t('activerecord.attributes.note.title')
      th = t('activerecord.attributes.note.tag')
      th = t('activerecord.attributes.note.created_by_user_id')
      th = t('activerecord.attributes.note.created_at')

  tbody
    - @notes.each do |note|
      tr
        td.center.favorite-note
          - if note.favorite_note?(current_user.id)
            #favorite-star
        td.title
          - if notification = current_user.comment_notifications(note).last
            = link_to notification_path(notification_id: notification, unread_comment_id: current_user.oldest_comment(note).id, note_id: note.id), class: 'unread-comment' do
              = note.title.truncate(65, omission: '...')
            i.fas.fa-info-circle.comment
          - elsif notification = current_user.note_notifications(note).last
            = link_to notification_path(notification_id: notification, note_id: note.id), class: 'unread-note' do
              = note.title.truncate(65, omission: '...')
            i.fas.fa-info-circle.created
          - else
            = link_to note.title.truncate(65, omission: '...'), note_url(note)
        td.tag-list
          = render 'notes/tag_list', tag_list: note.tag_list
        td.user-name
          = note.created_by_user.full_name
        td.created-at
          = l note.created_at

.center.pt10
  = paginate @notes

= javascript_include_tag 'notes/list'

app/views/notes/new.html.slim
= render 'common/form_errors', target: @note

div.form-title
  span.under_border = "#{ t('view.note') }#{ t('view.new') }"
  span.note-description_button.btn-sm.btn-secondary
    = t('helpers.about_markdown')

  div#overlay
  div#window
    div#inner
      div.note-description_text
        = render 'description_text'
      i.fas.fa-times.close

= render 'form'

app/views/notes/show.html.slim
div.form-title style='width: 1000px;'
  = hidden_field_tag :note_id, @note.id
  span.under_border = @note.title

- if current_user.favorite_notes.find_by(note_id: @note.id)
  = link_to t('view.release_favorite'), release_favorite_notes_path(note_id: @note.id), class: 'release-favorite-note-btn mt5'
- else
  = link_to t('view.add_favorite'), add_favorite_notes_path(note_id: @note.id), class: 'add-favorite-note-btn mt5'

div.comment-count
  = link_to '#comments' do
    i.far.fa-comment
    = @note.comments.count

div.editor-info
  span.editor-name
    i.fas.fa-user-edit
    = @note.created_by_user.full_name
  span.edit-time
      = l @note.created_at

div.tag-list
  = render 'notes/tag_list', tag_list: @note.tag_list

div.note-content-markdown.mb20
  div.content
    = markdown(@note.content)
    - if current_user == @note.created_by_user
      = link_to t('view.edit'), edit_note_url(@note), class: 'btn btn-info float-right'

div.comments
  = render partial: 'notes/user_note_comments/index', locals: { note: @note }, collection: @comments, as: 'comment'

div.comment-form
  = render 'notes/user_note_comments/form', note: @note, comment: @comment

div#toc

= javascript_include_tag 'notes/show'
= javascript_include_tag 'notes/user_note_comments/form'
= javascript_include_tag 'notes/user_note_comments/index'