config/routes.rb
Rails.application.routes.draw do
  mount Root => '/'
  mount GrapeSwaggerRails::Engine => '/docs' if defined? GrapeSwaggerRails
  devise_for :users
  root to: 'top#index'
  get 'common/preview', to: 'common#preview'
  get 'common/realtime_preview', to: 'common#realtime_preview'
  get 'user_note_comments/create_comment', to: 'user_note_comments#create_comment'
  get 'user_note_comments/update_comment', to: 'user_note_comments#update_comment'
  get 'user_note_comments/destroy_comment', to: 'user_note_comments#destroy_comment'
  get 'notification', to: 'notifications#confirm'

  resources :profiles, only: %i[edit update]
  resources :notes do
    collection do
      match :index, via: %i[get post]
      match 'create_new', to: 'notes#create', via: 'post'
      get :add_favorite
      get :release_favorite
    end
  end
end

app/views/layouts/_header.html.slim
div.header
  div.container_div
    div.layout-title
      = link_to t('view.title'), root_path

    div.layout-menu
      - if user_signed_in?
        ul.side-menu-tab.float-left
          li.sub-menu-main-li
            = t('view.header.note')
            ul.sub-menu-sub-li
              li
                = link_to t('view.index'), notes_path
              li
                = link_to t('view.new'), new_note_url
        div.notification-container
          i.bell.far.fa-bell#notify-bell
            div#balloon
              - if @notifications.present?
                .notifications
                  = render partial: 'layouts/notification', collection: @notifications, as: 'notification'
              - else
                .non-notification
                  = t('helpers.no_notifications')
          - if @notifications.present?
            div.badge.new
              = @notifications.count

    - if user_signed_in?
      = render 'layouts/my_menu_header'
    - else
      = link_to t('view.header.login'), new_user_session_url, class: 'login'

= stylesheet_link_tag 'layout'

app/views/layouts/_my_menu_header.html.slim
ul.side-menu-tab.float-right
  li.sub-menu-main-li
    = t('view.header.my_menu')
    ul.sub-menu-sub-li
      li
        = link_to t('view.header.profile'), edit_profile_url(current_user)
      li
        = link_to t('view.header.logout'), destroy_user_session_path, method: 'delete'

app/views/layouts/_notification.html.slim
- if notification.kind == 'comment'
  = link_to notification_path(notification_id: notification.id, unread_comment_id: current_user.oldest_comment(notification.note).id, note_id: notification.note.id), class: "comment-notification comment-#{ notification.comment.id }" do
    .notification-detail
      strong = notification.active_user.full_name
      | さんが
      strong 「#{ notification.note.title.truncate(30, omission: '...') }」
      | にコメントしました。
    span.created-time
      = l notification.created_at

- elsif notification.kind == 'note'
  = link_to notification_path(notification_id: notification.id, note_id: notification.note.id), class: 'note-notification' do
    .notification-detail
      strong = notification.active_user.full_name
      = t('helpers.new_note_notify')
      strong 「#{ notification.note.title.truncate(35, omission: '...') }」
    span.created-time
      = l notification.created_at

app/views/layouts/application.html.slim
doctype html
html
  head
    meta charset='utf-8'
    meta http-equiv='X-UA-Compatible' content='IE=Edge,chrome=1'
    meta http-equiv='content-language' content='ja'
    title Trecon-App
    = csrf_meta_tags

    = stylesheet_link_tag    'application', media: 'all'
    = include_gon
    = javascript_include_tag 'application'
    = render_lazybox

    div
    = render 'layouts/header'

    body
      .container_div
        - flash.each do |key, value|
          - status = key == 'notice' ? 'success' : 'danger'
          = content_tag(:div, class: "alert alert-#{ status } flash-span") do
            span.glyphicon.glyphicon-info-sign.pr10
            = value.html_safe
        = yield